/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mostafa
 */
public class AddNewPatient extends javax.swing.JFrame {

    /**
     * Creates new form AddNewPatient
     */
    public AddNewPatient() {
        super("EaseCare Clinic");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        AddPatientBtn = new javax.swing.JButton();
        PatientsListBtn = new javax.swing.JButton();
        AddDoctorBtn = new javax.swing.JButton();
        DoctorsListBtn = new javax.swing.JButton();
        AppointmentsBtn = new javax.swing.JButton();
        BillingsBtn = new javax.swing.JButton();
        VisitsBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        PatientName_edt = new javax.swing.JTextField();
        PatientAddress_edt = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        Gender_Combo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CAID_edt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 51, 102));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EaseCare Clinic");
        SidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/small-logo.png"))); // NOI18N
        SidePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        HomeBtn.setBackground(new java.awt.Color(0, 51, 102));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/home.png"))); // NOI18N
        HomeBtn.setText("Home Page");
        HomeBtn.setBorder(null);
        HomeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        HomeBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        SidePanel.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 30));

        AddPatientBtn.setBackground(new java.awt.Color(0, 51, 102));
        AddPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddPatientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/add_patient.png"))); // NOI18N
        AddPatientBtn.setText("Add New Patient ");
        AddPatientBtn.setBorder(null);
        AddPatientBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        AddPatientBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AddPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtnActionPerformed(evt);
            }
        });
        SidePanel.add(AddPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 30));

        PatientsListBtn.setBackground(new java.awt.Color(0, 51, 102));
        PatientsListBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PatientsListBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientsListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/patients.png"))); // NOI18N
        PatientsListBtn.setText("Patients List");
        PatientsListBtn.setBorder(null);
        PatientsListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PatientsListBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        PatientsListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsListBtnActionPerformed(evt);
            }
        });
        SidePanel.add(PatientsListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        AddDoctorBtn.setBackground(new java.awt.Color(0, 51, 102));
        AddDoctorBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddDoctorBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddDoctorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/add_doctor.png"))); // NOI18N
        AddDoctorBtn.setText("Add New Doctor");
        AddDoctorBtn.setBorder(null);
        AddDoctorBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        AddDoctorBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AddDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorBtnActionPerformed(evt);
            }
        });
        SidePanel.add(AddDoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 30));

        DoctorsListBtn.setBackground(new java.awt.Color(0, 51, 102));
        DoctorsListBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DoctorsListBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorsListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/doctors.png"))); // NOI18N
        DoctorsListBtn.setText("Doctors List");
        DoctorsListBtn.setBorder(null);
        DoctorsListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        DoctorsListBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        DoctorsListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsListBtnActionPerformed(evt);
            }
        });
        SidePanel.add(DoctorsListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 30));

        AppointmentsBtn.setBackground(new java.awt.Color(0, 51, 102));
        AppointmentsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AppointmentsBtn.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/appointments.png"))); // NOI18N
        AppointmentsBtn.setText(" Appointments");
        AppointmentsBtn.setBorder(null);
        AppointmentsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        AppointmentsBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AppointmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsBtnActionPerformed(evt);
            }
        });
        SidePanel.add(AppointmentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 30));

        BillingsBtn.setBackground(new java.awt.Color(0, 51, 102));
        BillingsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BillingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        BillingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/bills.png"))); // NOI18N
        BillingsBtn.setText("Manage Bills");
        BillingsBtn.setBorder(null);
        BillingsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BillingsBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        BillingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingsBtnActionPerformed(evt);
            }
        });
        SidePanel.add(BillingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 30));

        VisitsBtn.setBackground(new java.awt.Color(0, 51, 102));
        VisitsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        VisitsBtn.setForeground(new java.awt.Color(255, 255, 255));
        VisitsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/endvisit.png"))); // NOI18N
        VisitsBtn.setText("End Patient Visit");
        VisitsBtn.setBorder(null);
        VisitsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        VisitsBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        VisitsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitsBtnActionPerformed(evt);
            }
        });
        SidePanel.add(VisitsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 30));

        LogoutBtn.setBackground(new java.awt.Color(0, 51, 102));
        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/logout.png"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setBorder(null);
        LogoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        LogoutBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        SidePanel.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 180, 30));

        MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 513));

        TitlePanel.setBackground(new java.awt.Color(9, 124, 180));
        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add New Patient");
        TitlePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 18, 439, 86));

        MainPanel.add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Patient Name");
        MainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 100, 30));

        jLabel9.setBackground(new java.awt.Color(0, 51, 102));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Patient Gender");
        MainPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 120, 30));

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setText("Patient Address");
        MainPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 120, 30));

        PatientName_edt.setBackground(new java.awt.Color(255, 255, 255));
        PatientName_edt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PatientName_edt.setForeground(new java.awt.Color(0, 51, 102));
        MainPanel.add(PatientName_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 340, 30));

        PatientAddress_edt.setBackground(new java.awt.Color(255, 255, 255));
        PatientAddress_edt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        PatientAddress_edt.setForeground(new java.awt.Color(0, 51, 102));
        MainPanel.add(PatientAddress_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 340, 30));

        AddBtn.setBackground(new java.awt.Color(0, 51, 102));
        AddBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        MainPanel.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 140, 40));

        Gender_Combo.setBackground(new java.awt.Color(255, 255, 255));
        Gender_Combo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Gender_Combo.setForeground(new java.awt.Color(0, 51, 102));
        Gender_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        MainPanel.add(Gender_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 340, 30));

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Clinic Assistant ID");
        MainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, 130, 30));

        CAID_edt.setBackground(new java.awt.Color(255, 255, 255));
        CAID_edt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CAID_edt.setForeground(new java.awt.Color(0, 51, 102));
        MainPanel.add(CAID_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 340, 30));

        jLabel8.setBackground(new java.awt.Color(0, 51, 102));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Patient Birth Date");
        MainPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 140, 30));

        jLabel11.setBackground(new java.awt.Color(0, 51, 102));
        jLabel11.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Note: Added Patient will get ID by default (Auto Increment)");
        MainPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 460, 30));

        jDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser.setForeground(new java.awt.Color(0, 51, 102));
        jDateChooser.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        MainPanel.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 340, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(MainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        //String ID = PatientID_edt.getText();
        String Name = PatientName_edt.getText();
        String Gender = (String) Gender_Combo.getSelectedItem();
        String Address = PatientAddress_edt.getText();
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        String BitrhDate = date.format(jDateChooser.getDate());
        String CA_ID = CAID_edt.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata", "root", "admin123");
            Statement st = con.createStatement();
            String sql = ("insert into patient(name,gender,address,bDate,clinicassistant_id) values ('" + Name + "','" + Gender + "','" + Address + "','" + BitrhDate + "','" + CA_ID + "')");

            int rowAdded = st.executeUpdate(sql);

            if (rowAdded > 0) {
                JOptionPane.showMessageDialog(this, "Successfully New Patient has been added! ");
                PatientsList pl = new PatientsList();
                pl.showData();
            } else {
                JOptionPane.showMessageDialog(this, "Please Fill All rows correct, Try again!", "Failure", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        Home homePage = new Home();
        setVisible(false);
        homePage.setVisible(true);
        homePage.totalDoctors();
        homePage.totalPatients();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void AddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtnActionPerformed
        // TODO add your handling code here:
        AddNewPatient addNewPatient = new AddNewPatient();
        setVisible(false);
        addNewPatient.setVisible(true);
    }//GEN-LAST:event_AddPatientBtnActionPerformed

    private void PatientsListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsListBtnActionPerformed
        // TODO add your handling code here:
        PatientsList patientsList = new PatientsList();
        setVisible(false);
        patientsList.setVisible(true);

    }//GEN-LAST:event_PatientsListBtnActionPerformed

    private void AddDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorBtnActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("This For Clinic Assistant Only \n Please Enter the password: ");
        if (input.equals("admin1010")) {
            JOptionPane.showMessageDialog(null, "Matched Password, Welcome Clinic Assistant...");
            AddNewDoctor addNewDoctor = new AddNewDoctor();
            setVisible(false);
            addNewDoctor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, " Wrong Password! You can't Enter here", "Failure", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AddDoctorBtnActionPerformed

    private void DoctorsListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsListBtnActionPerformed
        // TODO add your handling code here:
        DoctorsList doctorsList = new DoctorsList();
        setVisible(false);
        doctorsList.setVisible(true);
    }//GEN-LAST:event_DoctorsListBtnActionPerformed

    private void AppointmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsBtnActionPerformed
        // TODO add your handling code here:
        ManageAppointments manageAppointments = new ManageAppointments();
        setVisible(false);
        manageAppointments.setVisible(true);
    }//GEN-LAST:event_AppointmentsBtnActionPerformed

    private void BillingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingsBtnActionPerformed
        // TODO add your handling code here:
        ManageBills manageBills = new ManageBills();
        setVisible(false);
        manageBills.setVisible(true);
    }//GEN-LAST:event_BillingsBtnActionPerformed

    private void VisitsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitsBtnActionPerformed
        // TODO add your handling code here:
        EndVisit endVisit = new EndVisit();
        setVisible(false);
        endVisit.setVisible(true);
    }//GEN-LAST:event_VisitsBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout ?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            FirstPanel first = new FirstPanel();
            setVisible(false);
            first.setVisible(true);
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewPatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewPatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton AddDoctorBtn;
    private javax.swing.JButton AddPatientBtn;
    private javax.swing.JButton AppointmentsBtn;
    private javax.swing.JButton BillingsBtn;
    private javax.swing.JTextField CAID_edt;
    private javax.swing.JButton DoctorsListBtn;
    private javax.swing.JComboBox<String> Gender_Combo;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField PatientAddress_edt;
    private javax.swing.JTextField PatientName_edt;
    private javax.swing.JButton PatientsListBtn;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton VisitsBtn;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
