/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mostafa
 */
public class EndVisit extends javax.swing.JFrame {

    /**
     * Creates new form EndVisit
     */
    public EndVisit() {
        super("EaseCare Clinic");
        initComponents();
        showData();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    public void showData() {
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata", "root", "admin123");
            Statement st = con.createStatement();
            String sql = "select *from clinicdata.treatment";
            ResultSet rs = st.executeQuery(sql);

            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            tblModel.setRowCount(0);

            while (rs.next()) {
                String patientID = String.valueOf(rs.getInt("patient_id"));
                String doctorID = String.valueOf(rs.getInt("doctor_id"));

                //String Array for store data into jTable
                String tbData[] = {patientID, doctorID};

                //Add String Array data into jTable
                tblModel.addRow(tbData);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        SidePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        HomeBtn = new javax.swing.JButton();
        AddPatientBtn = new javax.swing.JButton();
        PatientsListBtn = new javax.swing.JButton();
        AddDoctorBtn = new javax.swing.JButton();
        DoctorsListBtn = new javax.swing.JButton();
        AppointmentsBtn = new javax.swing.JButton();
        BillingsBtn = new javax.swing.JButton();
        VisitsBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        TitlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        patientid_edt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        doctorid_edt = new javax.swing.JTextField();
        endBtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SidePanel.setBackground(new java.awt.Color(0, 51, 102));
        SidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EaseCare Clinic");
        SidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 150, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/small-logo.png"))); // NOI18N
        SidePanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        HomeBtn.setBackground(new java.awt.Color(0, 51, 102));
        HomeBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/home.png"))); // NOI18N
        HomeBtn.setText("Home Page");
        HomeBtn.setBorder(null);
        HomeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        HomeBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });
        SidePanel.add(HomeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 180, 30));

        AddPatientBtn.setBackground(new java.awt.Color(0, 51, 102));
        AddPatientBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddPatientBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddPatientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/add_patient.png"))); // NOI18N
        AddPatientBtn.setText("Add New Patient ");
        AddPatientBtn.setBorder(null);
        AddPatientBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        AddPatientBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AddPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPatientBtnActionPerformed(evt);
            }
        });
        SidePanel.add(AddPatientBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 180, 30));

        PatientsListBtn.setBackground(new java.awt.Color(0, 51, 102));
        PatientsListBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        PatientsListBtn.setForeground(new java.awt.Color(255, 255, 255));
        PatientsListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/patients.png"))); // NOI18N
        PatientsListBtn.setText("Patients List");
        PatientsListBtn.setBorder(null);
        PatientsListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        PatientsListBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        PatientsListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientsListBtnActionPerformed(evt);
            }
        });
        SidePanel.add(PatientsListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 30));

        AddDoctorBtn.setBackground(new java.awt.Color(0, 51, 102));
        AddDoctorBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AddDoctorBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddDoctorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/add_doctor.png"))); // NOI18N
        AddDoctorBtn.setText("Add New Doctor");
        AddDoctorBtn.setBorder(null);
        AddDoctorBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        AddDoctorBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AddDoctorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorBtnActionPerformed(evt);
            }
        });
        SidePanel.add(AddDoctorBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 30));

        DoctorsListBtn.setBackground(new java.awt.Color(0, 51, 102));
        DoctorsListBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        DoctorsListBtn.setForeground(new java.awt.Color(255, 255, 255));
        DoctorsListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/doctors.png"))); // NOI18N
        DoctorsListBtn.setText("Doctors List");
        DoctorsListBtn.setBorder(null);
        DoctorsListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        DoctorsListBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        DoctorsListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorsListBtnActionPerformed(evt);
            }
        });
        SidePanel.add(DoctorsListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 30));

        AppointmentsBtn.setBackground(new java.awt.Color(0, 51, 102));
        AppointmentsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        AppointmentsBtn.setForeground(new java.awt.Color(255, 255, 255));
        AppointmentsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/appointments.png"))); // NOI18N
        AppointmentsBtn.setText(" Appointments");
        AppointmentsBtn.setBorder(null);
        AppointmentsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        AppointmentsBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        AppointmentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointmentsBtnActionPerformed(evt);
            }
        });
        SidePanel.add(AppointmentsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 180, 30));

        BillingsBtn.setBackground(new java.awt.Color(0, 51, 102));
        BillingsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        BillingsBtn.setForeground(new java.awt.Color(255, 255, 255));
        BillingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/bills.png"))); // NOI18N
        BillingsBtn.setText("Manage Bills");
        BillingsBtn.setBorder(null);
        BillingsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        BillingsBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        BillingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BillingsBtnActionPerformed(evt);
            }
        });
        SidePanel.add(BillingsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 180, 30));

        VisitsBtn.setBackground(new java.awt.Color(0, 51, 102));
        VisitsBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        VisitsBtn.setForeground(new java.awt.Color(255, 255, 255));
        VisitsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/endvisit.png"))); // NOI18N
        VisitsBtn.setText("End Patient Visit");
        VisitsBtn.setBorder(null);
        VisitsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        VisitsBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        VisitsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisitsBtnActionPerformed(evt);
            }
        });
        SidePanel.add(VisitsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 180, 30));

        LogoutBtn.setBackground(new java.awt.Color(0, 51, 102));
        LogoutBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/logout.png"))); // NOI18N
        LogoutBtn.setText("Logout");
        LogoutBtn.setBorder(null);
        LogoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        LogoutBtn.setPreferredSize(new java.awt.Dimension(240, 59));
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        SidePanel.add(LogoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 180, 30));

        MainPanel.add(SidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 513));

        TitlePanel.setBackground(new java.awt.Color(9, 124, 180));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("End Patient Visit");

        javax.swing.GroupLayout TitlePanelLayout = new javax.swing.GroupLayout(TitlePanel);
        TitlePanel.setLayout(TitlePanelLayout);
        TitlePanelLayout.setHorizontalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TitlePanelLayout.createSequentialGroup()
                .addContainerGap(303, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        TitlePanelLayout.setVerticalGroup(
            TitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TitlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        MainPanel.add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        jTabbedPane1.setForeground(new java.awt.Color(0, 51, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 51, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Doctor ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 51, 102));
        jTable1.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jTable1.setSelectionForeground(new java.awt.Color(0, 153, 153));
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 380));

        jTabbedPane1.addTab("Visits List", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(0, 51, 102));
        jLabel23.setFont(new java.awt.Font("Rockwell", 2, 17)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Filling this simple model means that:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 360, 30));

        jLabel24.setBackground(new java.awt.Color(0, 51, 102));
        jLabel24.setFont(new java.awt.Font("Rockwell", 2, 17)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("the patient (patient ID) was treated by the doctor (Doctor ID).");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 510, 30));

        jLabel17.setBackground(new java.awt.Color(0, 51, 102));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("Patient ID:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 30));

        patientid_edt.setBackground(new java.awt.Color(255, 255, 255));
        patientid_edt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        patientid_edt.setForeground(new java.awt.Color(0, 51, 102));
        jPanel2.add(patientid_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 340, 30));

        jLabel18.setBackground(new java.awt.Color(0, 51, 102));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 51, 102));
        jLabel18.setText("Doctor ID:");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 90, 30));

        doctorid_edt.setBackground(new java.awt.Color(255, 255, 255));
        doctorid_edt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        doctorid_edt.setForeground(new java.awt.Color(0, 51, 102));
        jPanel2.add(doctorid_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 340, 30));

        endBtn.setBackground(new java.awt.Color(0, 51, 102));
        endBtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        endBtn.setForeground(new java.awt.Color(255, 255, 255));
        endBtn.setText("End Visit");
        endBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBtnActionPerformed(evt);
            }
        });
        jPanel2.add(endBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 150, 50));

        jLabel25.setBackground(new java.awt.Color(0, 51, 102));
        jLabel25.setFont(new java.awt.Font("Rockwell", 2, 16)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Thank you Doctor, for your great efforts ");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 370, 30));

        jTabbedPane1.addTab("End Patient Visit", jPanel2);

        MainPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 590, 400));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(MainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void endBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBtnActionPerformed
        // TODO add your handling code here:
        String PatientID = patientid_edt.getText();
        String DoctorID = doctorid_edt.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata", "root", "admin123");
            Statement st = con.createStatement();
            String sql = ("insert into treatment values ('" + PatientID + "','" + DoctorID + "')");
            int rowAdded = st.executeUpdate(sql);

            if (rowAdded > 0) {
                JOptionPane.showMessageDialog(this, "Successfully Patient Visit has been ended! ");
                showData();
                st.close();
                con.close();
            } else {
                JOptionPane.showMessageDialog(this, "Please Fill All rows correct, Try again!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_endBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        // TODO add your handling code here:
        Home homePage = new Home();
        setVisible(false);
        homePage.setVisible(true);
        homePage.totalDoctors();
        homePage.totalPatients();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void AddPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPatientBtnActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("This For Clinic Assistant Only \n Please Enter the password: ");
        if (input.equals("admin1010")) {
            JOptionPane.showMessageDialog(null, "Matched Password, Welcome Clinic Assistant...");
            AddNewPatient addNewPatient = new AddNewPatient();
            setVisible(false);
            addNewPatient.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, " Wrong Password! You can't Enter here");
        }
    }//GEN-LAST:event_AddPatientBtnActionPerformed

    private void PatientsListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientsListBtnActionPerformed
        // TODO add your handling code here:
        PatientsList patientsList = new PatientsList();
        setVisible(false);
        patientsList.setVisible(true);

    }//GEN-LAST:event_PatientsListBtnActionPerformed

    private void AddDoctorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorBtnActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog("This For Clinic Assistant Only \n Please Enter the password: ");
        if (input.equals("admin1010")) {
            JOptionPane.showMessageDialog(null, "Matched Password, Welcome Clinic Assistant...");
            AddNewDoctor addNewDoctor = new AddNewDoctor();
            setVisible(false);
            addNewDoctor.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, " Wrong Password! You can't Enter here");
        }
    }//GEN-LAST:event_AddDoctorBtnActionPerformed

    private void DoctorsListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorsListBtnActionPerformed
        // TODO add your handling code here:
        DoctorsList doctorsList = new DoctorsList();
        setVisible(false);
        doctorsList.setVisible(true);
    }//GEN-LAST:event_DoctorsListBtnActionPerformed

    private void AppointmentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointmentsBtnActionPerformed
        // TODO add your handling code here:
        ManageAppointments manageAppointments = new ManageAppointments();
        setVisible(false);
        manageAppointments.setVisible(true);
    }//GEN-LAST:event_AppointmentsBtnActionPerformed

    private void BillingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillingsBtnActionPerformed
        // TODO add your handling code here:
        ManageBills manageBills = new ManageBills();
        setVisible(false);
        manageBills.setVisible(true);
    }//GEN-LAST:event_BillingsBtnActionPerformed

    private void VisitsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisitsBtnActionPerformed
        // TODO add your handling code here:
        EndVisit endVisit = new EndVisit();
        setVisible(false);
        endVisit.setVisible(true);
    }//GEN-LAST:event_VisitsBtnActionPerformed

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout ?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            FirstPanel first = new FirstPanel();
            setVisible(false);
            first.setVisible(true);
        }
    }//GEN-LAST:event_LogoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndVisit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndVisit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDoctorBtn;
    private javax.swing.JButton AddPatientBtn;
    private javax.swing.JButton AppointmentsBtn;
    private javax.swing.JButton BillingsBtn;
    private javax.swing.JButton DoctorsListBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton PatientsListBtn;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JButton VisitsBtn;
    private javax.swing.JTextField doctorid_edt;
    private javax.swing.JButton endBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField patientid_edt;
    // End of variables declaration//GEN-END:variables
}
