/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mostafa
 */
public class LoginDoctor extends javax.swing.JFrame {

    /**
     * Creates new form LoginDoctor
     */
    public LoginDoctor() {
        super("EaseCare Clinic");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Doctor_username = new javax.swing.JTextField();
        Doctor_password = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DoctorLoginBtn = new javax.swing.JButton();
        DoctorCancelBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Doctor_username.setBackground(new java.awt.Color(255, 255, 255));
        Doctor_username.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Doctor_username.setForeground(new java.awt.Color(0, 51, 102));
        Doctor_username.setText("Username");
        Doctor_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_usernameActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Doctor_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 230, 30));

        Doctor_password.setBackground(new java.awt.Color(255, 255, 255));
        Doctor_password.setForeground(new java.awt.Color(0, 51, 102));
        Doctor_password.setText("jPasswordField1");
        Doctor_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_passwordActionPerformed(evt);
            }
        });
        jLayeredPane1.add(Doctor_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 230, 30));

        jLabel4.setFont(new java.awt.Font("Eras Demi ITC", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/username-icon.png"))); // NOI18N
        jLayeredPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 90, 100));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/password_icon.png"))); // NOI18N
        jLayeredPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 70, 100));

        DoctorLoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        DoctorLoginBtn.setFont(new java.awt.Font("Cooper Black", 1, 15)); // NOI18N
        DoctorLoginBtn.setForeground(new java.awt.Color(0, 51, 102));
        DoctorLoginBtn.setText("Login");
        DoctorLoginBtn.setBorder(null);
        DoctorLoginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DoctorLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorLoginBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(DoctorLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 110, 40));

        DoctorCancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        DoctorCancelBtn.setFont(new java.awt.Font("Cooper Black", 1, 15)); // NOI18N
        DoctorCancelBtn.setForeground(new java.awt.Color(0, 51, 102));
        DoctorCancelBtn.setText("Cancel");
        DoctorCancelBtn.setBorder(null);
        DoctorCancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        DoctorCancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorCancelBtnActionPerformed(evt);
            }
        });
        jLayeredPane1.add(DoctorCancelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clinicgui/images/Login-Doctor.png"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 780, 410));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jLayeredPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Doctor_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_usernameActionPerformed

    private void Doctor_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_passwordActionPerformed

    private void DoctorLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorLoginBtnActionPerformed
        // TODO add your handling code here:
        String Doctorname = Doctor_username.getText();
        String Doctorpassword = new String(Doctor_password.getPassword());
        try {
            boolean flag = false;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata", "root", "admin123");
            Statement stmt = con.createStatement();
            String sql = "select name,password from clinicdata.doctor";
            ResultSet rs = stmt.executeQuery(sql);
            while (rs.next()) {
                String username = rs.getString("name");
                String password = rs.getString("password");
                if (Doctorname.equals(username) && Doctorpassword.equals(password)) {
                    flag = true;
                    break;
                }

            }
            if (flag) {
                JOptionPane.showMessageDialog(this, "Successfully Logged in! \nWelcome Doctor ...");
                Home homePage = new Home();
                setVisible(false);
                homePage.setVisible(true);
                homePage.loggedName.setText("Dr. " + this.Doctor_username.getText());
                homePage.totalDoctors();
                homePage.totalPatients();
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect Username or Password! \nPlease Try again ... ", "Failure", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "There is some problems, may be network problem \nPlease Try again ... ", "Failure", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DoctorLoginBtnActionPerformed

    private void DoctorCancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorCancelBtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to back to First Page ?", "Select", JOptionPane.YES_NO_OPTION);
        if (a == 0) {
            setVisible(false);
            new FirstPanel().setVisible(true);
        }
    }//GEN-LAST:event_DoctorCancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoctorCancelBtn;
    private javax.swing.JButton DoctorLoginBtn;
    private javax.swing.JPasswordField Doctor_password;
    private javax.swing.JTextField Doctor_username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
