/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clinicsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Mostafa
 */
public class MedicalRecord extends javax.swing.JFrame {

    /**
     * Creates new form MedicalRecord
     */
    public MedicalRecord() {
        super("EaseCare Clinic");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MainPanel = new javax.swing.JPanel();
        TitlePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pID_edt = new javax.swing.JTextField();
        bSugar_edt = new javax.swing.JTextField();
        bType_edt = new javax.swing.JTextField();
        hRate_edt = new javax.swing.JTextField();
        weight_edt = new javax.swing.JTextField();
        MrN_edt = new javax.swing.JTextField();
        backToPatientsListBtn = new javax.swing.JButton();
        patientid = new javax.swing.JTextField();
        showBtn = new javax.swing.JButton();
        bPressure_edt = new javax.swing.JTextField();
        available_txt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        height_edt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        dID_edt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        AddBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        HRate_edt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        PatientID_edt = new javax.swing.JTextField();
        DoctorID_edt = new javax.swing.JTextField();
        Weight_edt = new javax.swing.JTextField();
        Height_edt = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        BPressure_edt = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        SLevel_edt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bType_Combo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        udHeight_edt = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        udWeight_edt = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        udBPressure_edt = new javax.swing.JTextField();
        udHRate_edt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        udSLevel_edt = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        udPatientID_edt = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        udbType_Combo = new javax.swing.JComboBox<>();
        backToPatientsListBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TitlePanel.setBackground(new java.awt.Color(9, 124, 180));
        TitlePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Patient Medical Record");
        TitlePanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 15, 439, 54));

        MainPanel.add(TitlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(0, 51, 102));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 102));
        jLabel14.setText("Medical Record Number (MRN): ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        jLabel16.setBackground(new java.awt.Color(0, 51, 102));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("Blood pressure: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 35));

        jLabel22.setBackground(new java.awt.Color(0, 51, 102));
        jLabel22.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 102));
        jLabel22.setText("Heart Rate: ");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 38));

        jLabel21.setBackground(new java.awt.Color(0, 51, 102));
        jLabel21.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 102));
        jLabel21.setText("Blood Type: ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 51, 102));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setText("Doctor ID:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 29));

        jLabel17.setBackground(new java.awt.Color(0, 51, 102));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("Patient Weight: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 30));

        jLabel5.setBackground(new java.awt.Color(0, 51, 102));
        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Patient Information");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel24.setBackground(new java.awt.Color(0, 51, 102));
        jLabel24.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 102));
        jLabel24.setText("Blood sugar level:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 38));

        pID_edt.setEditable(false);
        pID_edt.setBackground(new java.awt.Color(255, 255, 255));
        pID_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        pID_edt.setForeground(new java.awt.Color(0, 51, 102));
        pID_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pID_edtActionPerformed(evt);
            }
        });
        jPanel1.add(pID_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 190, -1));

        bSugar_edt.setEditable(false);
        bSugar_edt.setBackground(new java.awt.Color(255, 255, 255));
        bSugar_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bSugar_edt.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.add(bSugar_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 190, -1));

        bType_edt.setEditable(false);
        bType_edt.setBackground(new java.awt.Color(255, 255, 255));
        bType_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bType_edt.setForeground(new java.awt.Color(0, 51, 102));
        bType_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bType_edtActionPerformed(evt);
            }
        });
        jPanel1.add(bType_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 210, -1));

        hRate_edt.setEditable(false);
        hRate_edt.setBackground(new java.awt.Color(255, 255, 255));
        hRate_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        hRate_edt.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.add(hRate_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 210, -1));

        weight_edt.setEditable(false);
        weight_edt.setBackground(new java.awt.Color(255, 255, 255));
        weight_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        weight_edt.setForeground(new java.awt.Color(0, 51, 102));
        weight_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_edtActionPerformed(evt);
            }
        });
        jPanel1.add(weight_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 190, -1));

        MrN_edt.setEditable(false);
        MrN_edt.setBackground(new java.awt.Color(255, 255, 255));
        MrN_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        MrN_edt.setForeground(new java.awt.Color(0, 51, 102));
        MrN_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MrN_edtActionPerformed(evt);
            }
        });
        jPanel1.add(MrN_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 420, -1));

        backToPatientsListBtn.setBackground(new java.awt.Color(0, 51, 102));
        backToPatientsListBtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        backToPatientsListBtn.setForeground(new java.awt.Color(255, 255, 255));
        backToPatientsListBtn.setText("Back to Patients List");
        backToPatientsListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToPatientsListBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backToPatientsListBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 200, 40));

        patientid.setBackground(new java.awt.Color(255, 255, 255));
        patientid.setFont(new java.awt.Font("Dialog", 2, 13)); // NOI18N
        patientid.setForeground(new java.awt.Color(0, 51, 102));
        patientid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        patientid.setText(" Patient ID");
        patientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientidActionPerformed(evt);
            }
        });
        jPanel1.add(patientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 130, 36));

        showBtn.setBackground(new java.awt.Color(0, 51, 102));
        showBtn.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        showBtn.setForeground(new java.awt.Color(255, 255, 255));
        showBtn.setText("Show");
        showBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showBtnActionPerformed(evt);
            }
        });
        jPanel1.add(showBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 70, 40));

        bPressure_edt.setEditable(false);
        bPressure_edt.setBackground(new java.awt.Color(255, 255, 255));
        bPressure_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bPressure_edt.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.add(bPressure_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, -1));

        available_txt.setEditable(false);
        available_txt.setBackground(new java.awt.Color(255, 255, 255));
        available_txt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        available_txt.setForeground(new java.awt.Color(0, 204, 0));
        available_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        available_txt.setBorder(null);
        available_txt.setCaretColor(new java.awt.Color(9, 124, 180));
        available_txt.setDisabledTextColor(new java.awt.Color(9, 124, 180));
        available_txt.setSelectedTextColor(new java.awt.Color(9, 124, 180));
        available_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                available_txtActionPerformed(evt);
            }
        });
        jPanel1.add(available_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 170, 30));

        jLabel15.setBackground(new java.awt.Color(0, 51, 102));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 102));
        jLabel15.setText("Patient Height: ");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, 30));

        height_edt.setEditable(false);
        height_edt.setBackground(new java.awt.Color(255, 255, 255));
        height_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        height_edt.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.add(height_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 210, -1));

        jLabel25.setBackground(new java.awt.Color(0, 51, 102));
        jLabel25.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 102));
        jLabel25.setText("Patient ID:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 29));

        dID_edt.setEditable(false);
        dID_edt.setBackground(new java.awt.Color(255, 255, 255));
        dID_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        dID_edt.setForeground(new java.awt.Color(0, 51, 102));
        dID_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dID_edtActionPerformed(evt);
            }
        });
        jPanel1.add(dID_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 210, -1));

        jTabbedPane1.addTab("Patient Information", jPanel1);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddBtn.setBackground(new java.awt.Color(0, 51, 102));
        AddBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Create");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel4.add(AddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 230, 40));

        jLabel6.setBackground(new java.awt.Color(0, 51, 102));
        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 26)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Create New Medical Record");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 360, -1));

        jLabel19.setBackground(new java.awt.Color(0, 51, 102));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setText("Patient ID:");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 29));

        HRate_edt.setBackground(new java.awt.Color(255, 255, 255));
        HRate_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        HRate_edt.setForeground(new java.awt.Color(0, 51, 102));
        HRate_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRate_edtActionPerformed(evt);
            }
        });
        jPanel4.add(HRate_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 210, -1));

        jLabel20.setBackground(new java.awt.Color(0, 51, 102));
        jLabel20.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 102));
        jLabel20.setText("Patient Weight: ");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 30));

        jLabel23.setBackground(new java.awt.Color(0, 51, 102));
        jLabel23.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 102));
        jLabel23.setText("Patient Height: ");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, 30));

        jLabel29.setBackground(new java.awt.Color(0, 51, 102));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 51, 102));
        jLabel29.setText("Blood pressure: ");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 30));

        jLabel30.setBackground(new java.awt.Color(0, 51, 102));
        jLabel30.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 51, 102));
        jLabel30.setText("Blood Type: ");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, -1));

        PatientID_edt.setBackground(new java.awt.Color(255, 255, 255));
        PatientID_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        PatientID_edt.setForeground(new java.awt.Color(0, 51, 102));
        PatientID_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientID_edtActionPerformed(evt);
            }
        });
        jPanel4.add(PatientID_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 520, -1));

        DoctorID_edt.setBackground(new java.awt.Color(255, 255, 255));
        DoctorID_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        DoctorID_edt.setForeground(new java.awt.Color(0, 51, 102));
        DoctorID_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorID_edtActionPerformed(evt);
            }
        });
        jPanel4.add(DoctorID_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 200, -1));

        Weight_edt.setBackground(new java.awt.Color(255, 255, 255));
        Weight_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Weight_edt.setForeground(new java.awt.Color(0, 51, 102));
        Weight_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Weight_edtActionPerformed(evt);
            }
        });
        jPanel4.add(Weight_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 190, -1));

        Height_edt.setBackground(new java.awt.Color(255, 255, 255));
        Height_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        Height_edt.setForeground(new java.awt.Color(0, 51, 102));
        Height_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Height_edtActionPerformed(evt);
            }
        });
        jPanel4.add(Height_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 210, -1));

        jLabel31.setBackground(new java.awt.Color(0, 51, 102));
        jLabel31.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 51, 102));
        jLabel31.setText("Doctor ID:");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 90, 30));

        jLabel32.setBackground(new java.awt.Color(0, 51, 102));
        jLabel32.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 51, 102));
        jLabel32.setText("Heart Rate: ");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, -1, 30));

        BPressure_edt.setBackground(new java.awt.Color(255, 255, 255));
        BPressure_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        BPressure_edt.setForeground(new java.awt.Color(0, 51, 102));
        BPressure_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPressure_edtActionPerformed(evt);
            }
        });
        jPanel4.add(BPressure_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 190, -1));

        jLabel33.setBackground(new java.awt.Color(0, 51, 102));
        jLabel33.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 51, 102));
        jLabel33.setText("Blood sugar level:");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 30));

        SLevel_edt.setBackground(new java.awt.Color(255, 255, 255));
        SLevel_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        SLevel_edt.setForeground(new java.awt.Color(0, 51, 102));
        SLevel_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SLevel_edtActionPerformed(evt);
            }
        });
        jPanel4.add(SLevel_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 190, -1));

        jLabel10.setBackground(new java.awt.Color(0, 51, 102));
        jLabel10.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 102));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Note: Added Medical Record will get MRN by default (Auto Increment)");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 510, 30));

        bType_Combo.setBackground(new java.awt.Color(255, 255, 255));
        bType_Combo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        bType_Combo.setForeground(new java.awt.Color(0, 51, 102));
        bType_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel4.add(bType_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 210, 30));

        jTabbedPane1.addTab("Create New Medical Record", jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        udHeight_edt.setBackground(new java.awt.Color(255, 255, 255));
        udHeight_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udHeight_edt.setForeground(new java.awt.Color(0, 51, 102));
        udHeight_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udHeight_edtActionPerformed(evt);
            }
        });
        jPanel2.add(udHeight_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 210, -1));

        jLabel28.setBackground(new java.awt.Color(0, 51, 102));
        jLabel28.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 102));
        jLabel28.setText("Patient Height: ");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, -1, 30));

        udWeight_edt.setBackground(new java.awt.Color(255, 255, 255));
        udWeight_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udWeight_edt.setForeground(new java.awt.Color(0, 51, 102));
        udWeight_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udWeight_edtActionPerformed(evt);
            }
        });
        jPanel2.add(udWeight_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, -1));

        jLabel34.setBackground(new java.awt.Color(0, 51, 102));
        jLabel34.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 51, 102));
        jLabel34.setText("Patient Weight: ");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel35.setBackground(new java.awt.Color(0, 51, 102));
        jLabel35.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 51, 102));
        jLabel35.setText("Blood pressure: ");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 30));

        udBPressure_edt.setBackground(new java.awt.Color(255, 255, 255));
        udBPressure_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udBPressure_edt.setForeground(new java.awt.Color(0, 51, 102));
        udBPressure_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udBPressure_edtActionPerformed(evt);
            }
        });
        jPanel2.add(udBPressure_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, -1));

        udHRate_edt.setBackground(new java.awt.Color(255, 255, 255));
        udHRate_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udHRate_edt.setForeground(new java.awt.Color(0, 51, 102));
        udHRate_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udHRate_edtActionPerformed(evt);
            }
        });
        jPanel2.add(udHRate_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 210, -1));

        jLabel36.setBackground(new java.awt.Color(0, 51, 102));
        jLabel36.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 51, 102));
        jLabel36.setText("Blood Type: ");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel37.setBackground(new java.awt.Color(0, 51, 102));
        jLabel37.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 51, 102));
        jLabel37.setText("Heart Rate: ");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, 30));

        udSLevel_edt.setBackground(new java.awt.Color(255, 255, 255));
        udSLevel_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udSLevel_edt.setForeground(new java.awt.Color(0, 51, 102));
        udSLevel_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udSLevel_edtActionPerformed(evt);
            }
        });
        jPanel2.add(udSLevel_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, -1));

        jLabel38.setBackground(new java.awt.Color(0, 51, 102));
        jLabel38.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 51, 102));
        jLabel38.setText("Blood sugar level:");
        jPanel2.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, 30));

        udPatientID_edt.setBackground(new java.awt.Color(255, 255, 255));
        udPatientID_edt.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udPatientID_edt.setForeground(new java.awt.Color(0, 51, 102));
        udPatientID_edt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                udPatientID_edtActionPerformed(evt);
            }
        });
        jPanel2.add(udPatientID_edt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 520, -1));

        jLabel39.setBackground(new java.awt.Color(0, 51, 102));
        jLabel39.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 51, 102));
        jLabel39.setText("Patient ID:");
        jPanel2.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 30));

        updateBtn.setBackground(new java.awt.Color(0, 51, 102));
        updateBtn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 160, 40));

        jLabel7.setBackground(new java.awt.Color(0, 51, 102));
        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Update New Medical Record");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 360, -1));

        udbType_Combo.setBackground(new java.awt.Color(255, 255, 255));
        udbType_Combo.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        udbType_Combo.setForeground(new java.awt.Color(0, 51, 102));
        udbType_Combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        jPanel2.add(udbType_Combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 210, 30));

        backToPatientsListBtn1.setBackground(new java.awt.Color(0, 51, 102));
        backToPatientsListBtn1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        backToPatientsListBtn1.setForeground(new java.awt.Color(255, 255, 255));
        backToPatientsListBtn1.setText("Back to Patients List");
        backToPatientsListBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToPatientsListBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(backToPatientsListBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 220, 40));

        jTabbedPane1.addTab("Update Medical Record", jPanel2);

        MainPanel.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 720, 430));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(MainPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pID_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pID_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pID_edtActionPerformed

    private void weight_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight_edtActionPerformed

    private void bType_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bType_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bType_edtActionPerformed

    private void patientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientidActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        //String MRN = MRN_edt.getText();
        String Height =  Height_edt.getText();
        String Weight = Weight_edt.getText();
        String Blood_Type = (String) bType_Combo.getSelectedItem();
        String Blood_Pressure =  BPressure_edt.getText();
        String Heart_Rate =  HRate_edt.getText(); 
        String Suger_Level = SLevel_edt.getText();
        String PatientID = PatientID_edt.getText();
        String DoctorID = DoctorID_edt.getText();

        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata","root","admin123");
            Statement st = con.createStatement();
            String sql =("insert into medicalrecord(height,weight,bloodType,bloodPressure,heartRate,sugarLevel,patient_id,doctor_id) values ('"+Height+"','"+Weight+"','"+Blood_Type+"','"+Blood_Pressure+"','"+Heart_Rate+"','"+Suger_Level+"','"+PatientID+"','"+DoctorID+"')");
            
            int rowAdded = st.executeUpdate(sql);

            if (rowAdded > 0){
            JOptionPane.showMessageDialog(this, "Successfully New Medical Record has been Created! ");
            }
            else {
            JOptionPane.showMessageDialog(this, "Please fill all rows correct, Try again!","Failure", JOptionPane.ERROR_MESSAGE);           
            }
        } 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void HRate_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRate_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRate_edtActionPerformed

    private void PatientID_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientID_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PatientID_edtActionPerformed

    private void DoctorID_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorID_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoctorID_edtActionPerformed

    private void Weight_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Weight_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Weight_edtActionPerformed

    private void Height_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Height_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Height_edtActionPerformed

    private void BPressure_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPressure_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPressure_edtActionPerformed

    private void backToPatientsListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToPatientsListBtnActionPerformed
        // TODO add your handling code here:
        PatientsList patientsList = new PatientsList();
        setVisible(false);
        patientsList.setVisible(true);
    }//GEN-LAST:event_backToPatientsListBtnActionPerformed

    private void SLevel_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SLevel_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SLevel_edtActionPerformed

    private void showBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showBtnActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(patientid.getText());
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata","root","admin123");
            Statement st = con.createStatement();
            String sql = "select * from medicalrecord where patient_id ='"+id+"'";
            st.executeQuery(sql);
            ResultSet rs = st.getResultSet();

            if(rs.next()){
                    MrN_edt.setText(String.valueOf(rs.getInt("MRN")));
                    height_edt.setText(String.valueOf(rs.getInt("height")));
                    weight_edt.setText(String.valueOf(rs.getInt("weight")));
                    bType_edt.setText(rs.getString("bloodType"));
                    bPressure_edt.setText(rs.getString("bloodPressure"));
                    hRate_edt.setText(String.valueOf(rs.getInt("heartRate")));
                    bSugar_edt.setText(rs.getString("sugarLevel"));
                    pID_edt.setText(String.valueOf(rs.getInt("patient_id")));
                    dID_edt.setText(String.valueOf(rs.getInt("doctor_id")));
                    
                    available_txt.setText("Patient ID Available");
                
            }
            else
            {
                JOptionPane.showMessageDialog(this, "This Patient ID doesn't have Medical Record! ","Failure", JOptionPane.ERROR_MESSAGE);
            }
            
        } 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_showBtnActionPerformed

    private void dID_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dID_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dID_edtActionPerformed

    private void MrN_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MrN_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MrN_edtActionPerformed

    private void available_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_available_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_available_txtActionPerformed

    private void udHeight_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udHeight_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udHeight_edtActionPerformed

    private void udWeight_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udWeight_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udWeight_edtActionPerformed

    private void udBPressure_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udBPressure_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udBPressure_edtActionPerformed

    private void udHRate_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udHRate_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udHRate_edtActionPerformed

    private void udSLevel_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udSLevel_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udSLevel_edtActionPerformed

    private void udPatientID_edtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_udPatientID_edtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_udPatientID_edtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        //String MRN = udMRN_edt.getText();
        String Height =  udHeight_edt.getText();
        String Weight = udWeight_edt.getText();
        String Blood_Type = (String) udbType_Combo.getSelectedItem();
        String Blood_Pressure =  udBPressure_edt.getText();
        String Heart_Rate =  udHRate_edt.getText(); 
        String Suger_Level = udSLevel_edt.getText();
        String PatientID = udPatientID_edt.getText();
        //String dID = udPatientID_edt.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/clinicdata","root","admin123");
            Statement st = con.createStatement();
            String sql ="update medicalrecord set height='"+Height+"',weight='"+Weight+"',bloodType='"+Blood_Type+"',bloodPressure='"+Blood_Pressure+"',heartRate='"+Heart_Rate+"',sugarLevel='"+Suger_Level+"'where patient_id='"+PatientID+"'";
            //String sql ="update medicalrecord set height='"+Height+"',weight='"+Weight+"',bloodType='"+Blood_Type+"',bloodPressure='"+Blood_Pressure+"',heartRate='"+Heart_Rate+"',sugarLevel='"+Suger_Level+"',doctor_id='"+dID+"'where patient_id='"+PatientID+"'";
            //String sql = "select * from medicalrecord where Patient_Patient_ID ='"+PatientID+"'";
            int rowsUpdated = st.executeUpdate(sql);

            if(rowsUpdated > 0){
                JOptionPane.showMessageDialog(this, "Medical Record updated successfully");    
            }
            else
            {
                JOptionPane.showMessageDialog(this, "This Patient ID not found! ","Failure", JOptionPane.ERROR_MESSAGE);
            }
            
        } 
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void backToPatientsListBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToPatientsListBtn1ActionPerformed
        // TODO add your handling code here:
        PatientsList patientsList = new PatientsList();
        setVisible(false);
        patientsList.setVisible(true);
    }//GEN-LAST:event_backToPatientsListBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MedicalRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MedicalRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField BPressure_edt;
    private javax.swing.JTextField DoctorID_edt;
    private javax.swing.JTextField HRate_edt;
    private javax.swing.JTextField Height_edt;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextField MrN_edt;
    private javax.swing.JTextField PatientID_edt;
    private javax.swing.JTextField SLevel_edt;
    private javax.swing.JPanel TitlePanel;
    private javax.swing.JTextField Weight_edt;
    private javax.swing.JTextField available_txt;
    private javax.swing.JTextField bPressure_edt;
    private javax.swing.JTextField bSugar_edt;
    private javax.swing.JComboBox<String> bType_Combo;
    private javax.swing.JTextField bType_edt;
    private javax.swing.JButton backToPatientsListBtn;
    private javax.swing.JButton backToPatientsListBtn1;
    private javax.swing.JTextField dID_edt;
    private javax.swing.JTextField hRate_edt;
    private javax.swing.JTextField height_edt;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pID_edt;
    private javax.swing.JTextField patientid;
    private javax.swing.JButton showBtn;
    private javax.swing.JTextField udBPressure_edt;
    private javax.swing.JTextField udHRate_edt;
    private javax.swing.JTextField udHeight_edt;
    private javax.swing.JTextField udPatientID_edt;
    private javax.swing.JTextField udSLevel_edt;
    private javax.swing.JTextField udWeight_edt;
    private javax.swing.JComboBox<String> udbType_Combo;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField weight_edt;
    // End of variables declaration//GEN-END:variables
}
